server.port=8081
# Nombre de la aplicación
spring.application.name=medicos

# Conexión a PostgreSQL en el puerto 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/mediflow
spring.datasource.username=postgres
spring.datasource.password=default

# Hibernate creará/actualizará las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true